version: 0.6.{build}
image: Visual Studio 2017
configuration: Release
skip_tags: true
pull_requests:
  do_not_increment_build_number: true  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: false
  project_feed: true
before_build:
  - dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
  provider: Environment
  name: NuGet KodeAid
  on:
    branch: master
