version: 0.6.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
before_build:
- nuget restore
- dotnet restore
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
deploy:
  provider: NuGet
  api_key:
    secure: /l+O39xKbteTtcuyht5JhE8yyLrzeoysLH9r+9r/ZnpY38ULs23tGHT/ukPUaFIJ
  skip_symbols: false
  on:
    branch: master
