version: 0.6.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
before_build:
- nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
  provider: Environment
  name: NuGet KodeAid
  on:
    branch: master
